# Generated by Django 4.2.4 on 2023-09-04 18:31

from django.db import migrations, models
import django.db.models.deletion
import recepvet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Tutor', max_length=200)),
                ('cpf', models.CharField(help_text='Digite apenas os dígitos do CPF', max_length=11, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Veterinário', max_length=200)),
                ('expert', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('ave', 'Ave'), ('peixe', 'Peixe'), ('exotico', 'Exótico')], max_length=7, verbose_name='Expecialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_nome', models.CharField(max_length=40, verbose_name='Nome do Animal')),
                ('status_sexo', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=5, verbose_name='Sexo')),
                ('status_gen', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('ave', 'Ave'), ('peixe', 'Peixe'), ('exotico', 'Exótico')], max_length=7, verbose_name='Classificação')),
                ('especie', models.CharField(help_text='Caso seja cão ou gato, ponha a raça, se não, a espécie.', max_length=100, verbose_name='Raça/Espécie')),
                ('peso', models.FloatField(help_text='Peso do animal em kg')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=recepvet.models.upload_imagem_animal)),
                ('sintoma', models.CharField(max_length=1000, verbose_name='Sintomas')),
                ('tipo_c', models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno')], max_length=8, verbose_name='Consulta ou Retorno')),
                ('tutor', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recepvet.tutor')),
                ('vet', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recepvet.vet')),
            ],
        ),
    ]
