# Generated by Django 4.2.4 on 2023-09-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepvet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='peso',
            field=models.FloatField(help_text='Peso do animal em kg', verbose_name='Peso'),
        ),
    ]
